disabled_rules:
  - cyclomatic_complexity
  - function_body_length
  - identifier_name
  - function_parameter_count
  - line_length
  - multiple_closures_with_trailing_closure
  - nesting
  - shorthand_operator
  - todo
  - type_body_length
  - type_name
  - weak_delegate
  - force_cast
  - legacy_constructor
  - notification_center_detachment
  - class_delegate_protocol

opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - comma
  - conditional_returns_on_newline
  - control_statement
  - convenience_type
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_xctest_method
  - fatal_error_message
  - file_name_no_space
  - function_default_parameter_at_end
  - identical_operands
  - implicit_return
  - legacy_random
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - overridden_super_call
  - prefer_zero_over_explicit_init
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_imports
  - switch_case_on_newline
  - toggle_bool
  - unowned_variable_capture
  - unused_import
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

excluded:
  - Pods

file_length:
  warning: 100000
  error: 1000000
