source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.1'
use_frameworks!
pod 'GoogleMaps'
pod 'PubNub'
pod 'DLRadioButton'
pod 'COBezierTableView'
pod 'MGSwipeTableCell'
pod 'Fabric'
pod 'Answers'
